export const ADD_CART = 'ADD_CART';
export const DELETE_CART = 'DELETE_CART';
export const LOAD_CART = 'LOAD_CART';
export const DESCREASE = 'DESCREATE';
export const CHOOSE_PRODUCT = 'CHOOSE_PRODUCT';
export const CLEAR_CHOSEN = 'CLEAR_CHOSEN';
export const DELETE_BUY_PRODUCTS = 'DELETE_BUY_PRODUCTS';

export default {
    ADD_CART,
    DELETE_CART,
    LOAD_CART,
    DESCREASE,
    CHOOSE_PRODUCT,
    CLEAR_CHOSEN,
    DELETE_BUY_PRODUCTS
}