const CLEAR_MESSAGES = 'CLEAR_MESSAGES';
const ADD_MASSAGES = 'ADD_MESSAGES';
const COUNT_NEW_MESSAGES = 'COUNT_NEW_MESSAGES';

export default {
    CLEAR_MESSAGES,
    ADD_MASSAGES,
    COUNT_NEW_MESSAGES
}